### ISSUE TITLE
Remove gateiowallet from blockList

### ISSUE THREAD

**Issue by arhag** [eosnetworkfoundation/evm-bridge-frontend#60]
Now that they support inline actions, we should not block them.

**Comment by Joshua2Mars** [comment]
Regarding the block list, we need to seperate EOS and USDT because the CEX may support only EOS. 

**Unsupported CEX for EOS**:
Kucoin: kucoindoteos
Binance: binancecleos
Bitget: bitgeteosdep
Bybit: bybitdeposit

**Warning List for EOS**:
Coinbase(coinbasebase)
Huobi Global(huobideposit)
OKX(okbtothemoon)
Gate(gateiowallet)
Kraken(krakenkraken)

**Unsupported CEX for USDT**:
Kucoin: kucoindoteos
Binance: binancecleos
Bitget: bitgeteosdep
Bybit: bybitdeposit
Coinbase(coinbasebase)
Huobi Global(huobideposit)
OKX(okbtothemoon)
Kraken(krakenkraken)

**Warning List for USDT**:
Gate(gateiowallet)
